/*
 * The contents of this file are subject to the Mozilla Public License 
 * Version 1.1 (the "License"); you may not use this file except in compliance 
 * with the License. You may obtain a copy of the License at 
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License 
 * for the specific language governing rights and
 * limitations under the License.
 *
 * The Original Code is "Java Security Component Framework"
 *
 * The Initial Developer of the Original Code are Thomas Wabner, alias waffel.
 * Portions created by Thomas Wabner are Copyright (C) 2004. 
 * 
 * All Rights Reserved.
 * Created on 21.01.2004
 *
 */
package org.waffel.jscf;

import java.io.InputStream;

/**
 * A container class, which is usually generated by executing a statement that
 * queries the JSCFramework.
 * <p>
 * The container holds one result stream and one error stream. If no error on a
 * execution of an statement occrus, the error stream can be null. If an error
 * on a execution of an statement occurs, the result stream can be null.
 * <p>
 * The container provides also an error indocator which should be first used, to
 * obtain if an error while executing a statement occurs.
 * 
 * @author waffel (Thomas Wabner)
 * @version $Id: JSCFResultSet.java,v 1.2 2006/02/06 17:32:32 waffel Exp $
 * @see org.waffel.jscf.JSCFStatement
 */
public interface JSCFResultSet {

    /**
     * Returns the result stream which is generated by the execution of an
     * statement. The statement itselfs put the reuslt in the result stream of
     * the <code>JSCFResultSet</code> object. If an error while the execution
     * process occurse, the result stream can be null.
     * 
     * @return the result stream, filled by a <code>JSCFStatement</code>. The
     *         result stream can be null. Check first, if an error has occured
     *         and then try to read from the stream.
     * @throws JSCFException
     *             if a JSCF access error occurs
     */
    InputStream getResultStream() throws JSCFException;

    /**
     * Returns the error stream which is generated by the execution of an
     * statement. The statement itselfs put the error in the error stream of the
     * <code>JSCFResultSet</code> object. If no error while the execution
     * process occurse, the error stream can be null.
     * 
     * @return the error stream, filled by a <code>JSCFStatement</code>. The
     *         error stream can be null. Check first, if an error has occured
     *         and then try to read from the stream.
     * @throws JSCFException
     *             if a JSCF access error occurs
     */
    InputStream getErrorStream() throws JSCFException;

    /**
     * Indicates if an error while the execution process from a
     * <code>JSCFStatement</code> occurs.
     * 
     * @return true if an error occurs, else false. This indicates not, if the
     *         error stream is not null or the result stream is not null!
     */
    boolean isError();

}
